#!/bin/bash

set -e

case "$1" in
   remove)
      rm -f /usr/bin/homeseer
      systemctl daemon-reload
      systemctl reset-failed
   ;;
   purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
      echo $1
    ;;
   *)
      echo "postinst called with unknown argument \`\$1'" >&2
      exit 0
   ;;
esac